/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI - version 0.1.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'knowledgeBaseManagement.get_all_knowledge_base_api_v1_kb_base_get': ['GET', '/api/v1/kb_base'],
  'knowledgeBaseManagement.create_knowledge_base_api_v1_kb_base_post': ['POST', '/api/v1/kb_base'],
  'knowledgeBaseManagement.delete_knowledge_base_api_v1_kb_base__kb_name__delete': [
    'DELETE',
    '/api/v1/kb_base/{kb_name}'
  ],
  'knowledgeBaseManagement.update_kb_schema_api_v1_kb_base__kb_name__schema_post': [
    'POST',
    '/api/v1/kb_base/{kb_name}/schema'
  ],
  'knowledgeBaseManagement.get_kb_schema_api_v1_kb_base__kb_name__schema_exists_get': [
    'GET',
    '/api/v1/kb_base/{kb_name}/schema/exists'
  ],
  'knowledgeBaseFileManagement.get_kb_files_api_v1_kb_base__kb_id__kb_file_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/kb_file'
  ],
  'knowledgeBaseFileManagement.upload_kb_file_api_v1_kb_base__kb_id__upload_file_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/upload_file'
  ],
  'knowledgeBaseFileManagement.get_uploaded_file_info_api_v1_kb_base__kb_id__upload_file__file_id__get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/upload_file/{file_id}'
  ],
  'knowledgeBaseFileManagement.ingest_kb_file_api_v1_kb_base__kb_id__ingest_file_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/ingest_file'
  ],
  'knowledgeBaseFileManagement.ingest_kb_data_api_v1_kb_base__kb_id__ingest_data_post': [
    'POST',
    '/api/v1/kb_base/{kb_id}/ingest_data'
  ],
  'knowledgeBaseDocumentChunkManagement.get_kb_file_chunks_api_v1_kb_base__kb_id__file__file_id__chunks_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/file/{file_id}/chunks'
  ],
  'knowledgeBaseDocumentChunkManagement.get_kb_chunks_api_v1_kb_base__kb_id__chunks_get': [
    'GET',
    '/api/v1/kb_base/{kb_id}/chunks'
  ],
  'knowledgeBaseRetrievalMethodDynamicManagement.create_kb_query_interface_api_v1_query_interface__kb_name__post': [
    'POST',
    '/api/v1/query_interface/{kb_name}'
  ],
  'knowledgeBaseRetrievalMethodDynamicManagement.get_kb_query_interface_api_v1_query_interface__kb_name__get': [
    'GET',
    '/api/v1/query_interface/{kb_name}'
  ],
  'annotationDataDeposit.deposit_data_api_v1_deposit_post': ['POST', '/api/v1/deposit'],
  'annotationDataDeposit.deposit_batch_api_v1_deposit_batch_post': ['POST', '/api/v1/deposit/batch'],
  'annotationDataManagement.get_data_list_api_v1_data_get': ['GET', '/api/v1/data'],
  'annotationDataManagement.get_data_by_id_api_v1_data__data_id__get': ['GET', '/api/v1/data/{data_id}'],
  'annotationDataManagement.update_annotation_api_v1_data__data_id__annotate_put': [
    'PUT',
    '/api/v1/data/{data_id}/annotate'
  ],
  'annotationDataManagement.approve_data_api_v1_data__data_id__approve_post': [
    'POST',
    '/api/v1/data/{data_id}/approve'
  ],
  'annotationDataManagement.reject_data_api_v1_data__data_id__reject_post': ['POST', '/api/v1/data/{data_id}/reject'],
  'annotationDataManagement.get_by_trace_id_api_v1_data_trace__trace_id__get': ['GET', '/api/v1/data/trace/{trace_id}'],
  'annotationDataManagement.get_by_group_id_api_v1_data_group__group_id__get': ['GET', '/api/v1/data/group/{group_id}'],
  'annotationDataManagement.get_groups_summary_api_v1_data_groups_summary_get': ['GET', '/api/v1/data/groups/summary'],
  'annotationKbIngestion.ingest_to_kb_api_v1_kb_data__data_id__ingest_post': [
    'POST',
    '/api/v1/kb/data/{data_id}/ingest'
  ],
  'annotationKbIngestion.get_kb_status_api_v1_kb_status_get': ['GET', '/api/v1/kb/status'],
  'annotationStatistics.get_overall_stats_api_v1_stats_get': ['GET', '/api/v1/stats'],
  'annotationStatistics.get_pending_p0_stats_api_v1_stats_pending_p0_get': ['GET', '/api/v1/stats/pending-p0'],
  'annotationStatistics.get_stats_by_type_api_v1_stats_by_type_get': ['GET', '/api/v1/stats/by-type'],
  'trigger.create_trigger_api_v1_trigger__kb_name___post': ['POST', '/api/v1/trigger/{kb_name}/'],
  'trigger.get_triggers_api_v1_trigger__kb_name___get': ['GET', '/api/v1/trigger/{kb_name}/'],
  'trigger.get_trigger_api_v1_trigger__kb_name___trigger_id__get': ['GET', '/api/v1/trigger/{kb_name}/{trigger_id}'],
  'trigger.update_trigger_api_v1_trigger__kb_name___trigger_id__put': ['PUT', '/api/v1/trigger/{kb_name}/{trigger_id}'],
  'trigger.delete_trigger_api_v1_trigger__kb_name___trigger_id__delete': [
    'DELETE',
    '/api/v1/trigger/{kb_name}/{trigger_id}'
  ],
  'trigger.enable_trigger_api_v1_trigger__kb_name___trigger_id__enable_patch': [
    'PATCH',
    '/api/v1/trigger/{kb_name}/{trigger_id}/enable'
  ],
  'trigger.disable_trigger_api_v1_trigger__kb_name___trigger_id__disable_patch': [
    'PATCH',
    '/api/v1/trigger/{kb_name}/{trigger_id}/disable'
  ],
  'trigger.manual_trigger_api_v1_trigger__kb_name___trigger_id__manual_post': [
    'POST',
    '/api/v1/trigger/{kb_name}/{trigger_id}/manual'
  ],
  'trigger.query_history_by_kb_api_v1_trigger_history__kb_name__get': ['GET', '/api/v1/trigger/history/{kb_name}'],
  'trigger.query_history_by_trigger_api_v1_trigger_history__kb_name___trigger_id__get': [
    'GET',
    '/api/v1/trigger/history/{kb_name}/{trigger_id}'
  ],
  'trigger.get_trigger_stats_api_v1_trigger_stats__kb_name__get': ['GET', '/api/v1/trigger/stats/{kb_name}'],
  'logConfiguration.get_current_log_level_api_v1_log_level_get': ['GET', '/api/v1/log/level'],
  'logConfiguration.set_log_level_endpoint_api_v1_log_level_post': ['POST', '/api/v1/log/level']
};
